### ISSUE TITLE
Could you add auto login?

### ISSUE THREAD

**Issue by junk87** [hearsilent/KUAS-AP-Material#46]
And people don't type then they can log in.
I think is more convenience for people,
So could you add this function? 
Please.

**Comment by abc873693** [comment]
I will release this function in next update.
Thank your suggestion.

**Comment by hearsilent** [comment]
@mick3773 Waiting for fix conflicts (#48), will merge it ASAP.

**Comment by hearsilent** [comment]
https://github.com/NKUST-ITC/KUAS-AP-Material/pull/48
